### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by fotrjhay** [navisecdelta/EmailGen#1]
Traceback (most recent call last):
	2: from EmailGen.rb:3:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- mechanize (LoadError)

**Comment by pry0cc** [comment]
Hey!

You need to install mechanize.

`gem install mechanize`, or run `bundle install`.
